version: "3"
services:
  test:
    image: "legman-kafka"
    build: .
    depends_on:
    - kafka
  leakage:
    image: "legman-kafka"
    build: .
    command: npm run leakage
    depends_on:
    - kafka
  lint:
    image: "legman-kafka"
    build: .
    command: npm run lint
  example:
    image: "legman-kafka"
    environment:
      LOGSTASH_HOSTNAME: "kafka"
    depends_on:
      - kafka
    build: .
    command: sh -c "cd example && npx tsc -p . && node ."

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
    - 2181

  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zookeeper
    expose:
      - 9092
    environment:
      KAFKA_CREATE_TOPICS: "example:30:1:compact,test:30:1:compact,leakage:30:1:compact" # name:partitions:replicas:log-compaction
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
